### PR TITLE
Java liberty stack update feb2022

### PR DESCRIPTION
**Pull request by ajm01**
### What does this PR do?:
_added outer loop deploy commands and contexts to devfiles for demonstrating deploy thoughts for the liberty stacks_

### Which issue(s) this PR fixes:
_n/a_

### PR acceptance criteria:

- [x] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [x] Test automation
_the javaliberty and websphere-liberty tests all pass_
- [x] Documentation
_Does any documentation need to be updated with your changes? - no_

### How to test changes / Special notes to the reviewer:

### CODE REVIEW

**Comment by elsony** [comment]
Looks like the following issues are blocking this PR from running:
https://github.com/redhat-developer/odo/issues/5451
https://github.com/redhat-developer/odo/issues/5450
https://github.com/redhat-developer/odo/issues/5452
We'll wait for those issues to be resolved before merging to avoid failing on the `odo deploy` command

**Comment by johnmcollier** [comment]
@ajm01 can you rebase?

**Comment by thepetk** [comment]
closing this PR as it's fairly old. If is a requirement feel free to re-open :)

**Pull request closed without merging**
