### PR TITLE
add dotnet6.0 sample

### PR DESCRIPTION
**Pull request by yangcao77**
Signed-off-by: Stephanie <yangcao@redhat.com>

### What does this PR do?:
_Summarize the changes. Are any stacks or samples added or updated?_
this PR adds .NET 6.0 sample to the registry

### Which issue(s) this PR fixes:
_Link to github issue(s)_
HAS issue:https://issues.redhat.com/projects/DEVHAS/issues/DEVHAS-79?filter=allopenissues 

### PR acceptance criteria:

- [ ] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_
- [] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:

### CODE REVIEW

**Review by rohitkrai03 — APPROVED** [review]

**Review by ibuziuk — APPROVED** [review]
sorry, my bad 
this was UD related issue - https://github.com/eclipse-che/che-dashboard/pull/551
thank you for addressing the issues with devfile. LGTM

**Review by amisevsk — APPROVED** [review]
Haven't tested all commands in the devfile but generally LGTM.

What's the purpose of the 
```yaml
      deployment/replicas: 1
      deployment/route: route1
      deployment/storageLimit: 400Mi
      deployment/storageRequest: 200Mi
      deployment/cpuLimit: "2"
      deployment/cpuRequest: 700m
      deployment/memoryLimit: 500Mi
      deployment/memoryRequest: 400Mi
      deployment/container-port: 8081
```
attributes in the kubernetes components in that devfile?

**Comment by yangcao77** [comment]
> Haven't tested all commands in the devfile but generally LGTM.
> 
> What's the purpose of the
> 
> ```yaml
>       deployment/replicas: 1
>       deployment/route: route1
>       deployment/storageLimit: 400Mi
>       deployment/storageRequest: 200Mi
>       deployment/cpuLimit: "2"
>       deployment/cpuRequest: 700m
>       deployment/memoryLimit: 500Mi
>       deployment/memoryRequest: 400Mi
>       deployment/container-port: 8081
> ```
> 
> attributes in the kubernetes components in that devfile?

The attributes are for appstudio, since devfile library does not have parser for Kubernetes inlined/uri content, those attributes are temporarily being used to store those config. and will be eventually moved to Kubernetes yaml after https://github.com/devfile/api/issues/755 been implemented.

**Comment by amisevsk** [comment]
> The attributes are for appstudio, since devfile library does not have parser for Kubernetes inlined/uri content, those attributes are temporarily being used to store those config. and will be eventually moved to Kubernetes yaml after https://github.com/devfile/api/issues/755 been implemented.

I suppose I'm not clear on why those attributes are applied to the service component:
```yaml
  - name: outerloop-service
    attributes:
      deployment/replicas: 1
      deployment/route: route1
      deployment/storageLimit: 400Mi
      deployment/storageRequest: 200Mi
      deployment/cpuLimit: "2"
      deployment/cpuRequest: 700m
      deployment/memoryLimit: 500Mi
      deployment/memoryRequest: 400Mi
      deployment/container-port: 8081
    kubernetes:
      uri: kubernetes/service.yaml
```

**Comment by yangcao77** [comment]
@amisevsk  That's actually because HAS implementation is the simplest approach; when update configurations in devfile, it adds the attributes to all kubernetes components; and when read from devfile, it assumes all kubernetes components will have the same attributes and will only read from the first component. 

I know it's confusing by just looking into the devfile, but since this is just a temporary workaround, we plan not to complicated the HAS logic and we will eventually get rid of the attributes and move to use kubernetes yaml instead.

**Comment by yangcao77** [comment]
@jerolimov Can console team help review this PR as well? Thanks!

**Review by jerolimov — APPROVED** [review]
@yangcao77 sorry for the delay. Tested the repo in the remote git folder and that builds fine. :+1:

The change here looks also fine for me.

**Pull request merged**
