### PR TITLE
add dockerfile to support offline registry builds

### PR DESCRIPTION
**Pull request by mike-hoang**
### What does this PR do?:
_Summarize the changes. Are any stacks or samples added or updated?_

Adds a dockerfile that packages resources and updates the devfiles to use the packaged resources.

### Which issue(s) this PR fixes:
_Link to github issue(s)_
https://github.com/devfile/api/issues/329

### PR acceptance criteria:

- [x] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [x] Test automation
_Does this repository's tests pass with your changes?_
- [x] Documentation
_Does any documentation need to be updated with your changes?_
- [x] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:

### CODE REVIEW

**Comment by thepetk** [comment]
Should we flag this PR as DO NOT MERGE, because it expects that first the work of https://github.com/devfile/registry-support/pull/179 has been merged.

**Comment by mike-hoang** [comment]
Holding this PR until all child tasks are completed from https://github.com/devfile/api/issues/329 as this would be the entry point for creating the offline build with all the new changes to the buildscripts

**Review by thepetk — CHANGES_REQUESTED** [review]

**Review by michael-valdron — APPROVED** [review]
/lgtm

After https://github.com/devfile/devfile-web/pull/92 is merged we should provide a reference to the devfile registy offline installation guide under the [README](https://github.com/mike-hoang/registry/blob/e2e01a1d3df3efb30cbb21ac965dafa3d30c68ee/README.md?plain=1#L29-L34).

**Pull request merged**
