### PR TITLE
bump up e2e-tests to latest

### PR DESCRIPTION
**Pull request by thepetk**
### What does this PR do?:

This PR bumps up the `redhat-appstudio/e2e-tests` dependency to the `v0.0.0-20240216111832-81d6508c8820` in order to address the CVE mentioned in the related issue.

### Which issue(s) this PR fixes:

fixes https://github.com/devfile/api/issues/1427

### PR acceptance criteria:

- [ ] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_
- [ ] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:

### CODE REVIEW

**Review by michael-valdron — COMMENTED** [review]
Should we merge https://github.com/redhat-appstudio/e2e-tests/pull/1043 first? Since it is the direct dependency tied to runc?

**Comment by thepetk** [comment]
> Should we merge [redhat-appstudio/e2e-tests#1043](https://github.com/redhat-appstudio/e2e-tests/pull/1043) first? Since it is the direct dependency tied to runc?

Tried to trace where the `opencontainers/runc` is used as direct dependency. What I found is that is being used inside `github.com/docker/docker`, which is a direct dependency of `github.com/openshift/oc` (which is a direct dependency of e2e-tests).

As the [redhat-appstudio/e2e-tests#1043](https://github.com/redhat-appstudio/e2e-tests/pull/1043) is pretty much the same PR like here I've closed it, because the rest of the dependencies related to the `runc` one haven't been updated yet. The PR pretty much tries to update the `runc` dependency to latest by:

```go get -u github.com/opencontainers/runc```

**Comment by thepetk** [comment]
> Should we merge [redhat-appstudio/e2e-tests#1043](https://github.com/redhat-appstudio/e2e-tests/pull/1043) first? Since it is the direct dependency tied to runc?

UPDATE: @michael-valdron after the update of the `runc` dependency in the `e2e-tests` repo (commit [here](f4a60d4cd578a8048805f5b05e6643d74fc17352)) I think is better if we follow your suggestion and just update the `e2e-tests` dependency.

**Review by michael-valdron — APPROVED** [review]
/lgtm

**Pull request merged**
