### PR TITLE
[java-maven] Use LTS JDK 17 image

### PR DESCRIPTION
**Pull request by rm3l**
### What does this PR do?:
This updates the container image to `registry.access.redhat.com/ubi9/openjdk-17`, to keep up with the latest JDK LTS, security-wise.

### Which issue(s) this PR fixes:
&mdash;

### PR acceptance criteria:

- [x] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [x] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_
- [x] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_
Tested with `odo`.

### How to test changes / Special notes to the reviewer:

### CODE REVIEW

**Comment by kadel** [comment]
Similarly as in https://github.com/devfile/registry/pull/169 I think it might be better to keep the old versions

**Comment by rm3l** [comment]
> Similarly as in #169 I think it might be better to keep the old versions

Done. I hesitated to do so in the beginning mainly because of the maintenance overhead, but yes, it makes sense to keep the old version. The default version of the stack still points to the old 1.2.0, but let me know if you think this should be changed.

**Review by kadel — APPROVED** [review]

**Comment by rm3l** [comment]
Same discussion as in https://github.com/devfile/registry/pull/169 applies here, about changing the default version.

As agreed with the rest of the team, I'm switching the default version of this stack to 1.3.0 (the one still on Devfile 2.1.0, but with a more recent JDK 17), for backward compatibility with the samples.

**Pull request merged**
