### PR TITLE
Add a 2.2.2 devfile version and set https endpoint to Spring Boot stack

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?:
Add a 2.2.2 devfile version and set https endpoint to Spring Boot stack.

### Which issue(s) this PR fixes:
1. Fix outdated "schemaVersion" attribute
2. Fix "Application is not available" error when launch Spring Boot application using Dev Spaces 3.12.0 / Eclipse Che Next"
Screenshot from 2024-04-15 15-59-05

_Note_: It was necessary to truncate the endpoint name to handle the maximum endpoint name length limitation of 15 characters.

### PR acceptance criteria:

- [x] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [x] Documentation
_Does any documentation need to be updated with your changes?_
- [x] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:

### CODE REVIEW

**Review by thepetk — COMMENTED** [review]
Looks good to me. @kadel as you are the stack owner could you please review the PR?

/hold

**Comment by dmytro-ndp** [comment]
FYI: ["v4.13-images", "v4.13-registry-test" tests above](https://github.com/devfile/registry/pull/367#issuecomment-2058658813) had failed because of known chectl deployment issue https://github.com/eclipse-che/che/issues/22921

**Pull request merged**
