### PR TITLE
Update registry repo CI to use proper build script

### PR DESCRIPTION
**Pull request by johnmcollier**
Looks like when we moved the build script from this repo to registry-support/build-tools, we never updated the CI in this repo.

### CODE REVIEW

**Review by GeekArthur — COMMENTED** [review]
The PR looks good to me, just one more question, if we switch to use build-tools to build the devfile-index image, should we delete the `build.sh` and `push.sh` scripts in this repo as those are old scripts and we won't use them any more?

**Comment by johnmcollier** [comment]
@GeekArthur D'oh, those should've been deleted 🤦‍♂️

**Comment by johnmcollier** [comment]
Updated!

**Review by GeekArthur — APPROVED** [review]
Thanks for making the changes, LGTM!

**Pull request merged**
