### PR TITLE
Add default stack and tools review owners

### PR DESCRIPTION
**Pull request by elsony**
Signed-off-by: eyuen <eyuen@redhat.com>

### What does this PR do?:
Add default stack and tools review owners. No devfile/stack changes

### Which issue(s) this PR fixes:
[_Link to github issue(s)_](https://github.com/devfile/api/issues/807)

### PR acceptance criteria:

- [x] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [x] Documentation
_Does any documentation need to be updated with your changes?_ No

### How to test changes / Special notes to the reviewer:
Invites have been sent to the Devfile Reviewers group to provide read access which is required for the reviewer.

### CODE REVIEW

**Comment by elsony** [comment]
Switched to use OWNERS file

**Comment by elsony** [comment]
@kadel I have moved to use OWNERS file. Please review again.

**Comment by kadel** [comment]
> @kadel I have moved to use OWNERS file. Please review again.

Some of the reviews needs to be invited to the github org

- Christoph
- tmds
- BethGriggs
- rohitkrai03

**Comment by elsony** [comment]
> Some of the reviews needs to be invited to the github org
> 
> * Christoph
> * tmds
> * BethGriggs
> * rohitkrai03

Invite has been sent. Waiting for them to accept.

**Comment by elsony** [comment]
@kadel I have fixed the owners list so all owner ids are valid now.

**Review by maysunfaisal — APPROVED** [review]

**Pull request merged**
