### PR TITLE
[go] Add debug command to Devfile

### PR DESCRIPTION
**Pull request by rm3l**
### What does this PR do?:
This adds a missing `debug` command to the Go stack.

### Which issue(s) this PR fixes:
&mdash;

### PR acceptance criteria:

- [x] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [x] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_
- [x] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_
Checked with `odo`.

### How to test changes / Special notes to the reviewer:
Running `odo dev --debug` and attaching a remote debugger to the local port forwarded by odo should work:

image

### CODE REVIEW

**Comment by kadel** [comment]
I would keep the old versions there as they are and added new versions with the changes.

**Comment by rm3l** [comment]
> I would keep the old versions there as they are and added new versions with the changes.

Done. I hesitated to do so in the beginning mainly because of the maintenance overhead, but yes, it makes sense to add new versions. I haven't changed the default version for now.

**Comment by kim-tsao** [comment]
> > I would keep the old versions there as they are and added new versions with the changes.
> 
> Done. I hesitated to do so in the beginning mainly because of the maintenance overhead, but yes, it makes sense to add new versions. I haven't changed the default version for now.

Yes, let's keep the default versions as-is for now.  The Devfile samples may be dependent on them as parents and may affect parsing when moving up to a newer parent version (as I've encountered).  We will need to perform additional testing and/or modify the samples to get them to work.

**Pull request merged**
