### PR TITLE
Fix tags for Java stack images

### PR DESCRIPTION
**Pull request by thepetk**
### What does this PR do?:

It specifies the tags for 3 different stacks:
- `java-maven` (from `registry.access.redhat.com/ubi8/openjdk-11:latest` to `registry.access.redhat.com/ubi8/openjdk-11:1.15`)
- `java-quarkus` (from `registry.access.redhat.com/ubi8/openjdk-17:latest` to `registry.access.redhat.com/ubi8/openjdk-17:1.15`)
- `java-springboot` (from `registry.access.redhat.com/ubi8/openjdk-11:latest` to `registry.access.redhat.com/ubi8/openjdk-11:1.15`)

### Which issue(s) this PR fixes:
Fixes https://github.com/devfile/api/issues/849

### PR acceptance criteria:

- [x] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [x] Documentation
_Does any documentation need to be updated with your changes?_
- [x] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:

I've tested all updates locally with `odo init` and `odo dev` in order to ensure that they are running correctly with the specified tag.

### CODE REVIEW

**Comment by thepetk** [comment]
Note, inside the [issue](https://github.com/devfile/api/issues/849) we have pointed out the `vert.x` image that needs update. I see that is using the [next](https://quay.io/repository/eclipse/che-java11-maven?tab=tags&tag=next) tag. IDK if this has to be updated to.

**Review by michael-valdron — CHANGES_REQUESTED** [review]
> Note, inside the [issue](https://github.com/devfile/api/issues/849) we have pointed out the `vert.x` image that needs update. I see that is using the [next](https://quay.io/repository/eclipse/che-java11-maven?tab=tags&tag=next) tag. IDK if this has to be updated to.

Based on https://github.com/devfile/api/issues/849#issuecomment-1529763304 and the age of the image tag compared to this comment I would say yes. I might bring up a topic of discussion as to why this image being used is very old and if there is a reason for it.

Use to latest fixed version for now, `7.37.2` looks like.

**Comment by thepetk** [comment]
Thanks @michael-valdron :) A question that I have regarding the changes we make is if we should define a process (if we haven't yet) of monitoring to our stack images tags, in order to ensure that they are always updated.

**Comment by thepetk** [comment]
Most probably the tests are failing because of https://github.com/devfile/api/issues/1115

**Review by michael-valdron — COMMENTED** [review]
/lgtm

Validate stacks are be failing due to: https://github.com/devfile/api/issues/1115

Will approve once this issue is resolved.

**Review by michael-valdron — APPROVED** [review]
/lgtm

**Pull request merged**
