### PR TITLE
Add dotnet60 stack

### PR DESCRIPTION
**Pull request by tmds**
### What does this PR do?:
Adds a stack for .NET 6.0 which will be released this week.
This is a copy of the `dotnet50` stack with `5` replaced by `6` in the devfile.

### PR acceptance criteria:

- [x] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_

@kadel @johnmcollier ptal.

### CODE REVIEW

**Comment by johnmcollier** [comment]
Hi @tmds, can alternate image to `registry.access.redhat.com/ubi8/dotnet-60:6.0` be used?

It looks like it requires authentication against registry.redhat.io to pull (at least outside of OpenShift):
```
johncollier@jcollier-mac ~ % docker pull registry.access.redhat.com/ubi8/dotnet-60:6.0
Error response from daemon: unsupported: This repo requires terms acceptance and is only available on registry.redhat.io
```

and we generally want to avoid any container registries that will require authentication to pull from (such as registry.redhat.io), for the community devfile registry.

**Comment by tmds** [comment]
@johnmcollier can you try again? The images got pushed yesterday. It should work now.

**Pull request merged**
