### PR TITLE
Update nodejs-svelte stack

### PR DESCRIPTION
**Pull request by svor**
### What does this PR do?:

Updates nodejs-svelte stack:
- Add new version 1.2.1
- Set https protocol for the endpoint
- Set 1.2.1 version as a default one

screenshot-che-dogfooding apps che-dev x6e0 p1 openshiftapps com-2024 03 20-12_34_10

screenshot-svor-nodejs-svelte-https-svelte apps che-dev x6e0 p1 openshiftapps com-2024 03 20-12_33_09

### Which issue(s) this PR fixes:
https://github.com/eclipse/che/issues/22869

### PR acceptance criteria:

- [ ] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_
- [ ] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:
Try it out on Developer Sandbox:

[Contribute](https://workspaces.openshift.com/#/https://raw.githubusercontent.com/devfile/registry/sv-update-svelte/stacks/nodejs-svelte/1.2.1/devfile.yaml)

### CODE REVIEW

**Comment by thepetk** [comment]
@svor there's an ongoing issue with the `nodejs` icon. Will be fixed after the completion of https://github.com/devfile/api/issues/1484

**Comment by thepetk** [comment]
> @svor there's an ongoing issue with the `nodejs` icon. Will be fixed after the completion of [devfile/api#1484](https://github.com/devfile/api/issues/1484)

@svor FYI the `nodejs` issue is now fixed.

**Comment by svor** [comment]
@thepetk thank you, I've updated my PR with latest changes with the nodejs icon fix.
Can I have a review please

**Review by thepetk — APPROVED** [review]
/lgtm Tested locally with `odo dev` & `minikube` and it worked fine.

**Pull request merged**
