### PR TITLE
Fix Maven version in description of Java Maven stack

### PR DESCRIPTION
**Pull request by apupier**
https://catalog.redhat.com/software/containers/ubi9/openjdk-17/61ee7c26ed74b2ffb22b07f6?image=65a90783d59cca758b7d8d64&container-tabs=packages https://catalog.redhat.com/software/containers/ubi8/openjdk-11/5dd6a4b45a13461646f677f4?image=6639ed26fe2c35406921c084&container-tabs=packages

### What does this PR do?:
_Summarize the changes. Are any stacks or samples added or updated?_

### Which issue(s) this PR fixes:
_Link to github issue(s)_

### PR acceptance criteria:

- [ ] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_
- [ ] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:

### CODE REVIEW

**Comment by apupier** [comment]
I'm wondering if we should not remove the Maven version as I do not think it is very important

**Review by thepetk — COMMENTED** [review]
LGTM +1 on not removing the Maven version. @kadel could you please review as the owner of the stack?

**Review by svor — APPROVED** [review]

**Comment by Jdubrick** [comment]
> LGTM +1 on not removing the Maven version. @kadel could you please review as the owner of the stack?

Bump @kadel

**Review by kadel — APPROVED** [review]

**Pull request merged**
