### PR TITLE
Use maven wrapper script instead of the mvn in java-quarkus commands

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?:
In order to fix the maven build in the java quarkus sample, modify the devfile commands with maven wrapper script instead of the pure `mvn` call, see: https://github.com/eclipse-che/che/issues/22961

### Which issue(s) this PR fixes:
fixes https://github.com/eclipse-che/che/issues/22961
fixes devfile/api#1541

### PR acceptance criteria:

- [ ] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_
- [ ] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:

### CODE REVIEW

**Review by ibuziuk — APPROVED** [review]

**Comment by maxandersen** [comment]
That works, but what's there reason the default is 3.8.5?

**Comment by vinokurig** [comment]
> That works, but what's there reason the default is 3.8.5?

This is the maven version from the image: `registry.access.redhat.com/ubi8/openjdk-17:1.18-2`

**Review by michael-valdron — COMMENTED** [review]
I'd recommend omitting changes to deprecated stack versions.

Otherwise, changes looks good to me.

**Comment by vinokurig** [comment]
@michael-valdron All the java-quarkus devfiles have been updated.

**Review by michael-valdron — COMMENTED** [review]
> @michael-valdron All the java-quarkus devfiles have been updated.

I'd recommend omitting these changes for deprecated versions `1.3.0` and `1.4.0`, change is minor so I won't let this block the PR.

I can approve once the stack owner has signed off.

cc @maxandersen

**Comment by vinokurig** [comment]
@michael-valdron 
> I'd recommend omitting these changes for deprecated versions 1.3.0 and 1.4.0, change is minor so I won't let this block the PR.

Sorry, I misunderstood your previous comment, reverted the `1.3.0` and `1.4.0` versions.

**Comment by lmilbaum** [comment]
issues are not enabled on this repo. Piggy backing on this PR. 
Please opt-out the `platform-engineering-bot` user. It is replaced by a renovate team bot user.

**Comment by michael-valdron** [comment]
> issues are not enabled on this repo. Piggy backing on this PR. Please opt-out the `platform-engineering-bot` user. It is replaced by a renovate team bot user.

Continuing this thread here: https://github.com/devfile/api/issues/1565#issuecomment-2123540452

**Review by Jdubrick — COMMENTED** [review]
lgtm just need stack owner @maxandersen approval

**Review by maxandersen — APPROVED** [review]
+1 though this means it will use the non-product supported maven.

**Comment by vinokurig** [comment]
@michael-valdron Could you please merge the PR if you do not have any objections?

**Review by michael-valdron — APPROVED** [review]
/lgtm

**Pull request merged**
