### PR TITLE
Update `Maven Java` stack

### PR DESCRIPTION
**Pull request by azatsarynnyy**
### What does this PR do?:
_Summarize the changes. Are any stacks or samples added or updated?_
- update schema to `2.2.2`;
- use `https` protocol for the `java-maven` devfile

### Which issue(s) this PR fixes:
_Link to github issue(s)_
https://github.com/eclipse-che/che/issues/22869

### PR acceptance criteria:

- [ ] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_
- [ ] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:
https://workspaces.openshift.com/#https://raw.githubusercontent.com/azatsarynnyy/registry/java-maven-update/stacks/java-maven/1.3.1/devfile.yaml

### CODE REVIEW

**Comment by azatsarynnyy** [comment]
also, I opened https://github.com/odo-devfiles/springboot-ex/pull/5

**Review by Jdubrick — COMMENTED** [review]
Bumping from `1.3.0` to `1.3.1` to contain schema change + http -> https is identical to what was done here for example: 
[go 1.2.0](https://github.com/devfile/registry/blob/66a5a95fd64f0173e085faf26f4a7bad498cb713/stacks/go/1.2.0/devfile.yaml) -> [go 1.2.1](https://github.com/devfile/registry/blob/66a5a95fd64f0173e085faf26f4a7bad498cb713/stacks/go/1.2.1/devfile.yaml#L5)

Since it was done before for consistency I'm okay with this change but I do wonder if using a patch version for increasing the schema version is the right move instead of creating a new `1.4.0` stack? 

cc @michael-valdron @thepetk

**Review by svor — APPROVED** [review]
lgtm
screenshot-nimbusweb me-2024 06 04-09_58_01

**Review by thepetk — COMMENTED** [review]
in general lgtm now that we have bumped the devfile version.

@kadel as the owner of the stack could you please review the PR?

**Comment by ibuziuk** [comment]
@thepetk can we merge ?

**Review by ibuziuk — APPROVED** [review]

**Review by kadel — APPROVED** [review]

**Comment by thepetk** [comment]
> @thepetk can we merge ?

@ibuziuk I've pinged the owner directly. Once is approved by the stack owner I'll merge it :)

**Pull request merged**
