### PR TITLE
Update Liberty stack devfiles

### PR DESCRIPTION
**Pull request by mezarin**
### What does this PR do?:

Existing stack updated:
- java-openliberty
- java-openliberty-gradle

Updates:
Adding the use of variables, update image used, and command execution updates

New devfiles being added:
- java-websphereliberty
- java-websphereliberty-gradle

### Which issue(s) this PR fixes:
No issue.

### PR acceptance criteria:

- [ ] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_

### How to test changes / Special notes to the reviewer:

### CODE REVIEW

**Comment by mezarin** [comment]
FYI @scottkurz

**Review by scottkurz — APPROVED** [review]
LGTM

**Comment by mezarin** [comment]
@elsony, the tests that failed were not caused by the Liberty devfile additions/updates in this PR. The tests on the Liberty devfiles being added/updated were successful.

The failures experienced by Validate Devfiles / Test Minikube (pull_request) and ci/prow/v4.7-registry-test appear to be caused by stack `php-laravel` during odo push:
Executing devfile commands for component php-laravel-starter
 •  Executing install command "composer install"  ...
 ✗  Failed to start component with name "php-laravel-starter". Error: Failed to create the component: command execution failed: command execution failed: unable to execute the run command: unable to exec command [/bin/sh -c cd /project && composer install] ...

**Comment by elsony** [comment]
The test error is caused by https://github.com/devfile/api/issues/701. Given that rest of the tests passed, I am merging this one since the test error is not caused by this PR.

**Comment by mezarin** [comment]
Hi @elsony, I can see this PR's updates in the staging registry: https://registry.stage.devfile.io/viewer, but they have not made it to the official registry: https://registry.devfile.io/viewer. Please let me know if we need to do something on our end. Thanks.

**Pull request merged**
