### PR TITLE
Explicitly set java version as a query parameter in the java-quarkus zip urls

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?:
Explicitly set java version in the java-quarkus zip urls to java 17, in order to fix the error from the `init-compile` command:
```
INFO] Recompiling the module because of changed dependency.
[INFO] Compiling 2 source files with javac [debug release 21] to target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.345 s
[INFO] Finished at: 2024-04-12T10:05:13Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.12.1:compile (default-compile) on project code-with-quarkus: Fatal error compiling: error: release version 21 not supported -> [Help 1]
```

### Which issue(s) this PR fixes:
N/A

### PR acceptance criteria:

- [ ] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_
- [ ] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:

### CODE REVIEW

**Review by maxandersen — COMMENTED** [review]
+1 if java 17 is the default for the images.

Is there a reason not using 21 by default here?

**Comment by vinokurig** [comment]
> Is there a reason not using 21 by default here?

The `init-compile` command fails with java 21. The error is in the description.

**Review by ibuziuk — COMMENTED** [review]
unrelated to java version
@maxandersen do we need `-Djava.util.logging.manager=org.jboss.logmanager.LogManager` arg in the commands? 


````
ould not load Logmanager "org.jboss.logmanager.LogManager"
java.lang.ClassNotFoundException: org.jboss.logmanager.LogManager
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
        at java.logging/java.util.logging.LogManager$1.run(LogManager.java:239)
        at java.logging/java.util.logging.LogManager$1.run(LogManager.java:223)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.logging/java.util.logging.LogManager.<clinit>(LogManager.java:222)
        at java.logging/java.util.logging.Logger.demandLogger(Logger.java:649)
        at java.logging/java.util.logging.Logger.getLogger(Logger.java:718)
        at java.logging/java.util.logging.Logger.getLogger(Logger.java:702)
        at com.google.inject.internal.util.Stopwatch.<clinit>(Stopwatch.java:27)
        at com.google.inject.internal.InternalInjectorCreator.<init>(InternalInjectorCreator.java:62)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:69)
        at com.google.inject.Guice.createInjector(Guice.java:59)
        at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:481)
        at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:206)
        at org.apache.maven.cli.MavenCli.container(MavenCli.java:651)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] Scanning for projects...
[INFO] 
````

**Comment by maxandersen** [comment]
In the pom file? Yes. 
No other way to guarantee the performanct logger gets installed first. 

That should not give such error. When does that happen?

**Review by michael-valdron — CHANGES_REQUESTED** [review]
I think to follow versioning I'd suggest the following:
- Create patch version copies with the PR changes:
    - `1.3.1`
    - `1.4.1`
- Deprecate the base versions that are broken by adding the `Deprecated` tag:
    - [`1.3.0`](https://github.com/devfile/registry/blob/7ef133621b0e0df71811abcff21c970ffc44f93f/stacks/java-quarkus/1.3.0/devfile.yaml#L7)
    - [`1.4.0`](https://github.com/devfile/registry/blob/7ef133621b0e0df71811abcff21c970ffc44f93f/stacks/java-quarkus/1.4.0/devfile.yaml#L7)

See [deprecation example](https://github.com/devfile/registry-support/blob/cca4c9a81f8d52a6116b32bac5d00b3c693538a1/tests/registry/stacks/go/1.2.0/devfile.yaml#L12).

**Comment by vinokurig** [comment]
@michael-valdron
>I think to follow versioning I'd suggest the following:
>
>Create patch version copies with the PR changes:
>1.3.1
>1.4.1
>Deprecate the base versions that are broken by adding the Deprecated tag:
>[1.3.0](https://github.com/devfile/registry/blob/7ef133621b0e0df71811abcff21c970ffc44f93f/stacks/java->quarkus/1.3.0/devfile.yaml#L7)
>[1.4.0](https://github.com/devfile/registry/blob/7ef133621b0e0df71811abcff21c970ffc44f93f/stacks/java->quarkus/1.4.0/devfile.yaml#L7)
>See [deprecation example](https://github.com/devfile/registry->support/blob/cca4c9a81f8d52a6116b32bac5d00b3c693538a1/tests/registry/stacks/go/1.2.0/devfile.yaml#L12).
>
>This also mean 1.4.1 becomes the new default version.

Done

**Comment by vinokurig** [comment]
@michael-valdron do you have an idea why the tests are failing?

**Comment by michael-valdron** [comment]
@vinokurig 

The odo v2 failure is an ongoing issue we are tracking: https://github.com/devfile/api/issues/1514

The odo v3 failure seems to be triggerred by test case failures on the `redhat-product` starter project:

```
Summarizing 4 Failures:
  [FAIL] test starter projects from devfile stacks [It] stack: java-quarkus version: 1.3.0 starter: redhat-product
  /home/runner/work/registry/registry/tests/odov3/odo_test.go:263
  [FAIL] test starter projects from devfile stacks [It] stack: java-quarkus version: 1.4.0 starter: redhat-product
  /home/runner/work/registry/registry/tests/odov3/odo_test.go:263
  [FAIL] test starter projects from devfile stacks [It] stack: java-quarkus version: 1.3.1 starter: redhat-product
  /home/runner/work/registry/registry/tests/odov3/odo_test.go:263
  [FAIL] test starter projects from devfile stacks [It] stack: java-quarkus version: 1.4.1 starter: redhat-product
  /home/runner/work/registry/registry/tests/odov3/odo_test.go:263
```

In fact, almost looks like it could be the same issue causing https://github.com/devfile/api/issues/1514:

```
odo logs stderr: 
  [FAILED] in [It] - /home/runner/work/registry/registry/tests/odov3/odo_test.go:263 @ 04/24/24 14:24:43.977
  Executing: odo delete namespace -f btpymstq
  << Timeline

  [FAILED] Expected
      <*errors.errorString | 0xc0003280c0>: 
      http://127.0.0.1:44665/ did not return 200
      {
          s: "http://127.0.0.1:44665/ did not return 200",
      }
  to be nil
  In [It] at: /home/runner/work/registry/registry/tests/odov3/odo_test.go:263 @ 04/24/24 14:24:43.977
```

I'll open an issue to investigate this one as well. https://github.com/devfile/registry/pull/369 will temporarily skip odo testing on `java-quarkus` until these issues are resolved.

**Comment by michael-valdron** [comment]
Opened an issue tied to odo v3 test failures: https://github.com/devfile/api/issues/1533

FYI @vinokurig

**Comment by vinokurig** [comment]
@michael-valdron Thank you for the explanation, can we proceed with current changes?

**Review by michael-valdron — APPROVED** [review]
/lgtm

Tested deployments locally, works on both odo v2 and odo v3.

odo v2 with `java-quarkus v1.3.1` stack and `community` starter project:
image

odo v3 with `java-quarkus v1.4.1` stack and `community` starter project:
image

`redhat-product` starter project is failing but is not affected by these changes.

**Comment by vinokurig** [comment]
@michael-valdron Could you please merge?

**Review by ibuziuk — APPROVED** [review]

**Pull request merged**
