### PR TITLE
Use latest Java Spring Boot stack as default

### PR DESCRIPTION
**Pull request by apupier**
it was set to a previous version originally to use a schema version 2.1 but in fact the default version was already upgraded to 2.2 3 months ago https://github.com/devfile/registry/commit/db0c583c550b7b8bf5ef3f3afbb85ade165f0d8b

### What does this PR do?:
_Summarize the changes. Are any stacks or samples added or updated?_

### Which issue(s) this PR fixes:
_Link to github issue(s)_

### PR acceptance criteria:

- [ ] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_
- [ ] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:

### CODE REVIEW

**Review by thepetk — COMMENTED** [review]
I think here the separation between 1.x and 2.x stacks work differently. It's not necessary that the 1.x stacks will use the 2.1.x devfile schema only and so on.

Actually the 1.x stacks are using innerloop-only commands, while the 2.x stacks have innerloop+outerloop commands (https://devfile.io/docs/2.2.0/innerloop-vs-outerloop).

As some of the stack consumers use the current default, I'm not sure about the impact that this change might have. I'd suggest keeping the default as is, as it already uses the 2.2.x devfile schema version.

WDYT?

**Comment by apupier** [comment]
the default was set to the 1.x because of the limitation to schema version. Per comments on the commit, it is because not everything was ready for schema version 2.2 BUT 3 months ago, the latest 1.x and the default has been upgraded to use schema version 2.2. So either, there is still this limitation and we should switch back to schema version 2.1 on the 1.4.0 stack OR the limitation does not exist anymore and it sounds benefitials to move to latest 2.x stack which has a lot more pre-configured.

But in terms of impact, I do not know exactly, last time I played with that was several years ago so my knowledge is quite outdated.

**Comment by apupier** [comment]
new arguments to migrate to new version. i tried with a recent Camel Quarkus application and it is working with 2.2.0 stack but not the 1.4.0. With 1.4.0, on changes, it is trying to indefintely restart the application and  it is not picking changes

**Comment by thepetk** [comment]
> the default was set to the 1.x because of the limitation to schema version. Per comments on the commit, it is because not everything was ready for schema version 2.2 BUT 3 months ago, the latest 1.x and the default has been upgraded to use schema version 2.2. So either, there is still this limitation and we should switch back to schema version 2.1 on the 1.4.0 stack OR the limitation does not exist anymore and it sounds benefitials to move to latest 2.x stack which has a lot more pre-configured.
> 
> But in terms of impact, I do not know exactly, last time I played with that was several years ago so my knowledge is quite outdated.

I don't think this is the case anymore for the limitation tbh, so I'd say the 1.x can stay at the 2.2.x version. After latest changes many of the 1.x stack versions have already adopted these versions.

TBH I'm also in favor of adopting/improving the versioning of the stacks. Moving the default to the latest could be a good way to go. Although atm I'm not sure about the consumers and how this might affect them. For example we have https://github.com/devfile/api/issues/1524 opened.

I would like to open a spike issue, so we can investigate first potential impact with our major consumers before merging this PR.

**Comment by thepetk** [comment]
> > the default was set to the 1.x because of the limitation to schema version. Per comments on the commit, it is because not everything was ready for schema version 2.2 BUT 3 months ago, the latest 1.x and the default has been upgraded to use schema version 2.2. So either, there is still this limitation and we should switch back to schema version 2.1 on the 1.4.0 stack OR the limitation does not exist anymore and it sounds benefitials to move to latest 2.x stack which has a lot more pre-configured.
> > But in terms of impact, I do not know exactly, last time I played with that was several years ago so my knowledge is quite outdated.
> 
> I don't think this is the case anymore for the limitation tbh, so I'd say the 1.x can stay at the 2.2.x version. After latest changes many of the 1.x stack versions have already adopted these versions.
> 
> TBH I'm also in favor of adopting/improving the versioning of the stacks. Moving the default to the latest could be a good way to go. Although atm I'm not sure about the consumers and how this might affect them. For example we have [devfile/api#1524](https://github.com/devfile/api/issues/1524) opened.
> 
> I would like to open a spike issue, so we can investigate first potential impact with our major consumers before merging this PR.

@apupier after an investigation, I think there should be no problem to adopt the `2.2.0` `java-springboot` stack version as the `default`.

The PR needs approval from @devfile/che-team & the stack owner (@kadel )

**Comment by apupier** [comment]
> The PR needs approval from @devfile/che-team & the stack owner (@kadel )

bump @kadel

**Review by kadel — APPROVED** [review]

**Review by svor — APPROVED** [review]
LGTM

I see warning message: git is not installed, but it's not related to the current PR:
`Git not found. Install it or configure it using the "git.path" setting.`

All commands work as expected

screenshot-nimbusweb me-2024 07 23-13_03_20

**Review by thepetk — APPROVED** [review]
/lgtm

**Pull request merged**
