### PR TITLE
Changed the starterProjects name to appropriate ones.

### PR DESCRIPTION
**Pull request by callmetushar123**
What does this PR do?:
I have changed the starterProjects name from s2i-example to dotnet-example and dotnetcore-example in order to avoid confusion as requested.

Which issue(s) this PR fixes:
https://github.com/devfile/api/issues/676#issue-1052735689

In addition to this issue, I have also changed the starterProjects name in the dotnetcore31 yaml file from s2i-example to dotnetcore-example.

PR acceptance criteria:
[ Yes] Contributing guide
Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?

Since it's just updating the name of the starter project example, I didn't test the changes in Che as there is no change in the yaml files format.

How to test changes / Special notes to the reviewer:
I am new to this, please feel free to drop some advice if I made some mistake anywhere.

### CODE REVIEW

**Comment by callmetushar123** [comment]
@kadel I have just resolved my DCO issue can please again put the lgtm label?

**Comment by callmetushar123** [comment]
I am getting an error that references to python-django component. Can someone help me out? I didn't had this error on 28th.
cc: @kadel

**Comment by kadel** [comment]
I think that this has been fixed in `main` branch.
Can you please rebase your PR against the `main` branch? It should fix it

**Review by elsony — APPROVED** [review]

**Comment by callmetushar123** [comment]
Test cases are failing again. Any leads? Is it related to my changes or do I need to rebase again?
@kadel @elsony

**Comment by kadel** [comment]
@callmetushar123 The failing tests are not related to your PR. 
One is due to java-quarkus using old Java image and the other is a timeout when pulling large images from the image registry.

I've opened PR to fix both problems (this PR https://github.com/devfile/registry/pull/131 should fix the errors) /cc @elsony

**Comment by elsony** [comment]
Looking at the failure, you may be seeing the same pre-mature timeout issue as another PR. 
 You can try increasing the timeout as this PR: https://github.com/devfile/registry/pull/119/files#diff-78b2bf4a9f8b3e99399996413b879fc1ff3d23687222e9788f908209dc4d73ad

**Comment by callmetushar123** [comment]
@kadel please review the changes.

@elsony Thank you so much for the hint.

**Comment by callmetushar123** [comment]
Hello @kadel can you please review it so that it can get merged?

**Comment by callmetushar123** [comment]
@elsony I need a bit of help here. Did I mess up somewhere?

**Comment by johnmcollier** [comment]
@callmetushar123 No, you just need to rebase with Git

**Comment by callmetushar123** [comment]
@johnmcollier Did it just now. Hope it's all good now

**Review by johnmcollier — APPROVED** [review]
LGTM.

Will need to wait for CI to pass before merging

**Review by johnmcollier — APPROVED** [review]

**Comment by johnmcollier** [comment]
There's some ongoing issues with openshift ci, the tests passed through github actions so I'm gonna merge.

**Pull request merged**
