### PR TITLE
Update nodejs-nextjs stack

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?:
Updates `nodejs-nextjs` stack:

- Add new version: `1.2.1`
- Set `schemaVersion: 2.2.2`
- Set `https` protocol for the endpoint
- Set `1.2.1` version as a default one

image

### Which issue(s) this PR fixes:
https://github.com/eclipse/che/issues/22869

### PR acceptance criteria:

- [ ] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_
- [ ] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:
You can use the following link to start a workspace for testing:
https://workspaces.openshift.com/#https://raw.githubusercontent.com/RomanNikitenko/registry/update-nextjs/stacks/nodejs-nextjs/1.2.1/devfile.yaml

Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

rh-pre-commit.version: 2.2.0
rh-pre-commit.check-secrets: ENABLED

### CODE REVIEW

**Comment by michael-valdron** [comment]
@Jdubrick we'll need to rebase to your changes

FYI @RomanNikitenko

**Review by thepetk — COMMENTED** [review]
/ok-to-test

**Comment by thepetk** [comment]
@RomanNikitenko could you try to rebase with the latest main. That should fix the ci failure for odo3 check

**Comment by michael-valdron** [comment]
> Not sure if we would like to remove completely version `1.2.0` (remove the dir and its record in the `stack.yaml`) like we did in #342

@thepetk Prefer we don't completely remove stack versions but rather deprecate them.

**Review by thepetk — APPROVED** [review]
/lgtm @michael-valdron sgtm to keep the `1.2.0` as is and deprecate it soon. Tested locally and is ok.

**Comment by RomanNikitenko** [comment]
could someone merge
I don't have merge permissions...

**Pull request merged**
