### PR TITLE
python: add missing workingDir

### PR DESCRIPTION
**Pull request by kadel**
### Which issue(s) this PR fixes:
fixes https://github.com/devfile/api/issues/777
### PR acceptance criteria:

- [x] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [x] Test automation
_Does this repository's tests pass with your changes?_
- [x] Documentation
_Does any documentation need to be updated with your changes?_

### How to test changes / Special notes to the reviewer:

### CODE REVIEW

**Review by elsony — APPROVED** [review]
/lgtm

**Comment by johnmcollier** [comment]
CI failures due to known issue which has been fixed, I'm gonna merge this, no point retesting since the modified stacks (python, python-django) were fine.

**Pull request merged**
