### PR TITLE
Bump nodejs-basic schema version to 2.2.2

### PR DESCRIPTION
**Pull request by michael-valdron**
### What does this PR do?:
_Summarize the changes. Are any stacks or samples added or updated?_

Updates schema version to match sample devfile: https://github.com/nodeshift-starters/devfile-sample/pull/45

### Which issue(s) this PR fixes:
_Link to github issue(s)_

fixes devfile/api#1590

### PR acceptance criteria:

- [X] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_
- [ ] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:

### CODE REVIEW

**Review by Jdubrick — APPROVED** [review]
/lgtm

If all tests pass this is good to go

**Comment by michael-valdron** [comment]
/hold

ODC only supports up to `2.2.1`: https://github.com/michael-valdron/openshift-console/blob/1b1da7381671226f81d135987e45aa35c827a376/go.mod#L9

Going to revise my changes to the sample first, and I'll either close or revise this PR once that is done.

**Comment by michael-valdron** [comment]
> https://github.com/devfile/registry/pull/415#issuecomment-2150747124

FYI @Jdubrick

**Comment by michael-valdron** [comment]
No revisions needed here, closing this PR.

**Comment by michael-valdron** [comment]
See https://github.com/nodeshift-starters/devfile-sample/pull/46 for revision changes.

**Pull request closed without merging**
