### PR TITLE
Update OWNERS (remove myself)

### PR DESCRIPTION
**Pull request by jerolimov**
Thanks for adding me some years ago to review changes to the devfile registry. But I don't think I can help here regularly, and I never had.

I would be happy if the bot stopped requesting reviews from my side. Feel free to ping me in special cases on Slack or here, but I need to reduce notifications on GitHub a bit.

### CODE REVIEW

**Comment by thepetk** [comment]
FYI there's PR already open to update the logic around OWNERS files and replace them with the CODEOWNERS

**Review by ibuziuk — APPROVED** [review]

**Review by michael-valdron — APPROVED** [review]
/lgtm

**Comment by michael-valdron** [comment]
@jerolimov Do you have permissions to merge or need help merging?

**Comment by jerolimov** [comment]
@michael-valdron I have no permissions to merge it. I thought the bot will do it, but it would be nice if you can help to merge this mini pr ;)

**Pull request merged**
