### PR TITLE
Add "with a Devfile" to descriptions.

### PR DESCRIPTION
**Pull request by tmds**
This makes it more clear what the differences is with other options in the OpenShift developer catalog for the same language/runtime.

@kadel ptal.

### CODE REVIEW

**Comment by tmds** [comment]
> This makes it more clear what the differences is with other options in the OpenShift developer catalog for the same language/runtime.

For example:

dev catalog

**Comment by elsony** [comment]
Adding "with a Devfile" on the entries in the devfile registry looks redundant since those entries are from a devfile registry so it is obvious that the samples contain a devfile. In OpenShift developer catalog, there is already the type on the top right of each card to describe the type, e.g. Devfiles, Builder Images, Helm Charts. Is that clear enough already that it is a devfile sample?

**Comment by tmds** [comment]
> there is already the type on the top right of each card

I think it helps users pick between these options by being more descriptive about the difference.

This is similar to how the `Helm Chart` says: _A Helm chart to ..._.

**Comment by elsony** [comment]
Those entries are doing a live query on the public community registry: https://registry.devfile.io/
It will be strange when viewing the public community registry to have every entry have "with a devfile" at the end with is already implied.

**Comment by johnmcollier** [comment]
Yeah, since we need to display these in places outside of the OpenShift Console, I agree with Elson.

**Comment by tmds** [comment]
Another example, where it's even less clear one option is for using Helm:

image

**Comment by elsony** [comment]
Maybe the UI is missing the type information in that case, e.g. in the All services catalog, we have:
image
which will be clear enough without mentioning helm or devfile in the description.

**Comment by tmds** [comment]
The screenshot I shared is what you get when clicking 'View all samples':

image

> Maybe the UI is missing the type information in that case

Yes, the information is missing in this view.

**Comment by elsony** [comment]
I have created https://issues.redhat.com/browse/ODC-7198 to request adding the technology type information to the samples view.

**Pull request closed without merging**
