### PR TITLE
Add a 2.2.2 devfile version and set https endpoint to Python stack

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?:
Add a 2.2.2 devfile version and set https endpoint to Python stack

### Which issue(s) this PR fixes:
1) outdated "schemaVersion" attribute
2) "Application not found" error when launch Python application using Dev Spaces 3.12.0 / Eclipse Che Next

### PR acceptance criteria:

- [x] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [x] Test automation
_Does this repository's tests pass with your changes?_
- [x] Documentation
_Does any documentation need to be updated with your changes?_
- [x] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:
1) Open Python 2.1.0 devfile URL https://workspaces.openshift.com/#https://raw.githubusercontent.com/dmytro-ndp/registry/54b174151d16898ae07a380ef774ad46b5ad7196/stacks/python/2.1.0/devfile.yaml
2) Run terminal task `devfile: pip-install-requirements` after workspace has started.
3) Run terminal task `devfile: run-app` and open application in new tab.
4) Stop application.
5) Run terminal task `devfile: debug-py` and open application in new tab.

Repeat steps above with Python 3.0.0 devfile URL https://workspaces.openshift.com/#https://raw.githubusercontent.com/dmytro-ndp/registry/54b174151d16898ae07a380ef774ad46b5ad7196/stacks/python/3.0.0/devfile.yaml

### CODE REVIEW

**Review by Jdubrick — CHANGES_REQUESTED** [review]
We should create a new stack for these changes as an update to the schema version is a significant update. It would be best to create `2.2.0` and `3.1.0` stacks for this. Additionally, these new stacks will have to be added to https://github.com/devfile/registry/blob/main/stacks/python/stack.yaml

cc @thepetk @michael-valdron

**Comment by dmytro-ndp** [comment]
@Jdubrick : thank you for review!

I have applied your suggestion from [the comment above](https://github.com/devfile/registry/pull/358#pullrequestreview-1991758240).

**Comment by dmytro-ndp** [comment]
@johnmcollier : repository's tests seem to be passed.
Is there anything else I should do to get this PR merged?

**Review by Jdubrick — APPROVED** [review]

**Pull request merged**
