### PR TITLE
dont mention upstream quarkus

### PR DESCRIPTION
**Pull request by maxandersen**
just quarkus as no diff from this and rhbq when it comes to the starters.

### CODE REVIEW

**Review by elsony — APPROVED** [review]
/lgtm

**Comment by johnmcollier** [comment]
More CI flakes 😢 

/retest

**Comment by johnmcollier** [comment]
To be honest, the test run on minikube already passed, and this change wouldn't have any effect on the tests, so I'm fine merging this either way.

Since OpenShift CI has been kinda flaky for the past few test runs for us, I've marked the check as optional for now

**Review by johnmcollier — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
