### PR TITLE
Revise client name RHTAP to Konflux

### PR DESCRIPTION
**Pull request by michael-valdron**
### What does this PR do?:
_Summarize the changes. Are any stacks or samples added or updated?_

Changes the client name RHTAP to Konflux in client tests and documentation.

### Which issue(s) this PR fixes:
_Link to github issue(s)_

### PR acceptance criteria:

- [X] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [X] Documentation
_Does any documentation need to be updated with your changes?_
- [ ] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:

### CODE REVIEW

**Review by Jdubrick — APPROVED** [review]
/lgtm

**Comment by michael-valdron** [comment]
/hold

Needs https://github.com/openshift/release/pull/49400 to be merged.

**Comment by michael-valdron** [comment]
> /hold
> 
> Needs [openshift/release#49400](https://github.com/openshift/release/pull/49400) to be merged.

/unhold

Actually this should be merged _before_ [openshift/release#49400](https://github.com/openshift/release/pull/49400) can be.

**Pull request merged**
