### PR TITLE
Updates node stacks to use dev

### PR DESCRIPTION
**Pull request by schultzp2020**
### What does this PR do?:
Updates node stacks to use dev

### Which issue(s) this PR fixes:
N/A

### PR acceptance criteria:

- [ ] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_

### How to test changes / Special notes to the reviewer:

### CODE REVIEW

**Review by johnmcollier — APPROVED** [review]
CI failures unrelated to changes.

Approving.

**Review by johnmcollier — APPROVED** [review]

**Comment by johnmcollier** [comment]
CI failures unrelated to changes, merging.

**Comment by johnmcollier** [comment]
@kadel The CI didn't seem to report that as a failure though: 

> FAILURE: FAILED TESTS:  python java-quarkus

So even if those failures hadn't occurred, this issue wouldn't have been caught.

**Comment by kadel** [comment]
yeh, you are right. 
It is quite strange, as the URL returns the correct HTTP code 200, but it fails. 
This is going to be almost impossible to catch in the script :-/

**Pull request merged**
