### PR TITLE
update go version in ci and dockerfiles

### PR DESCRIPTION
**Pull request by Jdubrick**
### What does this PR do?:
_Summarize the changes. Are any stacks or samples added or updated?_
First of the PRs that will be opened in order to complete https://github.com/devfile/api/issues/1473. This PR specifically updates the CI workflows and Dockerfiles to use `go 1.19`. This PR also adds a badge to the readme that visually shows that `go 1.19` is being implemented.
### Which issue(s) this PR fixes:
_Link to github issue(s)_
fixes https://github.com/devfile/api/issues/1473
### PR acceptance criteria:

- [ ] Contributing guide
_Have you read the [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) and followed its instructions?_
- [ ] Test automation
_Does this repository's tests pass with your changes?_
- [ ] Documentation
_Does any documentation need to be updated with your changes?_
- [ ] Check Tools Provider
_Have you tested the changes with existing tools, i.e. Odo, Che, Console? (See [devfile registry contributing guide](https://github.com/devfile/registry/blob/main/CONTRIBUTING.md) on how to test changes)_

### How to test changes / Special notes to the reviewer:

Building the registry works properly with `go 1.19` and the workflows function.

### CODE REVIEW

**Review by michael-valdron — CHANGES_REQUESTED** [review]
Current changes looks good.

Some changes that needs addressing first before this can be merged:

1. Along with updating the Go version in the dockerfiles you'll need to also unfreeze the references to [`devfile-index-base`]() and [index generator]():
    - [index generator - .ci/Dockerfile#L28](https://github.com/devfile/registry/blob/0144f042e4cd380d1c2d684eb415357b9ebff1c7/.ci/Dockerfile#L28): remove `-b v1.1.0` from line and above comment about the freeze
    - [`devfile-index-base` - .ci/Dockerfile#38](https://github.com/devfile/registry/blob/0144f042e4cd380d1c2d684eb415357b9ebff1c7/.ci/Dockerfile#L38): revert tag back to `next` and remove above comment about the freeze
    - [index generator - .ci/Dockerfile.offline#L28](https://github.com/devfile/registry/blob/0144f042e4cd380d1c2d684eb415357b9ebff1c7/.ci/Dockerfile.offline#L28): remove `-b v1.1.0` from line and above comment about the freeze
    - [`devfile-index-base` - .ci/Dockerfile.offline#47](https://github.com/devfile/registry/blob/0144f042e4cd380d1c2d684eb415357b9ebff1c7/.ci/Dockerfile.offline#L47): revert tag back to `next` and remove above comment about the freeze
3. Update golang tag reference under [openshift/release](https://github.com/openshift/release/blob/b56fd29ba52144e6564f29b2e1f113e1b03d5add/ci-operator/config/devfile/registry/devfile-registry-main__v4.12.yaml#L14) to `golang-1.19` (currently very old `golang-1.16`) and update the prow job with `make jobs`

**Comment by Jdubrick** [comment]
> Current changes looks good.
> 
> Some changes that needs addressing first before this can be merged:
> 
> 1. Along with updating the Go version in the dockerfiles you'll need to also unfreeze the references to `devfile-index-base` and index generator:
>    
>    * [index generator - .ci/Dockerfile#L28](https://github.com/devfile/registry/blob/0144f042e4cd380d1c2d684eb415357b9ebff1c7/.ci/Dockerfile#L28): remove `-b v1.1.0` from line and above comment about the freeze
>    * [`devfile-index-base` - .ci/Dockerfile#38](https://github.com/devfile/registry/blob/0144f042e4cd380d1c2d684eb415357b9ebff1c7/.ci/Dockerfile#L38): revert tag back to `next` and remove above comment about the freeze
>    * [index generator - .ci/Dockerfile.offline#L28](https://github.com/devfile/registry/blob/0144f042e4cd380d1c2d684eb415357b9ebff1c7/.ci/Dockerfile.offline#L28): remove `-b v1.1.0` from line and above comment about the freeze
>    * [`devfile-index-base` - .ci/Dockerfile.offline#47](https://github.com/devfile/registry/blob/0144f042e4cd380d1c2d684eb415357b9ebff1c7/.ci/Dockerfile.offline#L47): revert tag back to `next` and remove above comment about the freeze
> 2. Update golang tag reference under [openshift/release](https://github.com/openshift/release/blob/b56fd29ba52144e6564f29b2e1f113e1b03d5add/ci-operator/config/devfile/registry/devfile-registry-main__v4.12.yaml#L14) to `golang-1.19` (currently very old `golang-1.16`) and update the prow job with `make jobs`

@michael-valdron would you like all of those to be included in this one PR? My initial thought was to have the different acceptance criteria for unfreezing and prow job updates to be separate PRs and that's why I left them out. If it's preferred to include all in this one I can do that :)

**Comment by michael-valdron** [comment]
> > Current changes looks good.
> > Some changes that needs addressing first before this can be merged:
> > 
> > 1. Along with updating the Go version in the dockerfiles you'll need to also unfreeze the references to `devfile-index-base` and index generator:
> >    
> >    * [index generator - .ci/Dockerfile#L28](https://github.com/devfile/registry/blob/0144f042e4cd380d1c2d684eb415357b9ebff1c7/.ci/Dockerfile#L28): remove `-b v1.1.0` from line and above comment about the freeze
> >    * [`devfile-index-base` - .ci/Dockerfile#38](https://github.com/devfile/registry/blob/0144f042e4cd380d1c2d684eb415357b9ebff1c7/.ci/Dockerfile#L38): revert tag back to `next` and remove above comment about the freeze
> >    * [index generator - .ci/Dockerfile.offline#L28](https://github.com/devfile/registry/blob/0144f042e4cd380d1c2d684eb415357b9ebff1c7/.ci/Dockerfile.offline#L28): remove `-b v1.1.0` from line and above comment about the freeze
> >    * [`devfile-index-base` - .ci/Dockerfile.offline#47](https://github.com/devfile/registry/blob/0144f042e4cd380d1c2d684eb415357b9ebff1c7/.ci/Dockerfile.offline#L47): revert tag back to `next` and remove above comment about the freeze
> > 2. Update golang tag reference under [openshift/release](https://github.com/openshift/release/blob/b56fd29ba52144e6564f29b2e1f113e1b03d5add/ci-operator/config/devfile/registry/devfile-registry-main__v4.12.yaml#L14) to `golang-1.19` (currently very old `golang-1.16`) and update the prow job with `make jobs`
> 
> @michael-valdron would you like all of those to be included in this one PR? My initial thought was to have the different acceptance criteria for unfreezing and prow job updates to be separate PRs and that's why I left them out. If it's preferred to include all in this one I can do that :)

@Jdubrick Unfreezing the references is part of the acceptance criteria for https://github.com/devfile/api/issues/1473 and would be needed to ensure the Go version update allows the latest changes to work, prow job updates would be a separate PR however because it is under openshift/release.

**Review by michael-valdron — APPROVED** [review]
/lgtm

**Pull request merged**
